### ISSUE TITLE
'gbk' codec can't decode

### ISSUE THREAD

**Issue by abbottjlu** [anhkgg/MovieHunter#1]
python2 main.py 疯狂的外星人
'gbk' codec can't decode bytes in position 2-3: illegal multibyte sequence
[-] search 疯狂的外星人 failed

OS 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"

**Comment by anhkgg** [comment]
因为在win下开发，编码问题自行解决一下，ubuntu应该是utf8
